[package]
name = "core"
version = "1.0.0"
authors = ["Ben Harris <mail@bharr.is>", "Matt Ickstadt <matt@icky.pw>", "Matt Coffin <mcoffin13@gmail.com>"]
build = "./build.rs"

[lib]
name = "core"
path = "rust/src/libcore/lib.rs"
